# application.yml
server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        bootstrap: true
        encrypt:
          enabled: true

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

# Basic Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Essential Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.web: INFO